version: '3.8'

services:
  loja-infantil:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loja-infantil
    ports:
      - "8025:8025"
    restart: unless-stopped
    networks:
      - loja-network

networks:
  loja-network:
    driver: bridge

